kind: pipeline
name: default

steps:
  - name: install
    image: node:11-alpine
    commands:
      - node -v
      - npm -v
      - touch test

  - name: build
    image: node:11-alpine
    commands:
      - npm run build:prod

  - name: copy
    image: appleboy/drone-scp
    host: nicco.io
    username: root
    port: 1312
    secrets: [ ssh_key ]
    target: /srv/web/home
    source:
      - ./public
      - ./docker-compose.yml
      - ./docker-compose.prod.yml
    when:
      event: push
      branch: master

  - name: run
    image: appleboy/drone-ssh
    host: nicco.io
    username: root
    port: 1312
    secrets: [ ssh_key ]
    script:
      - cd /srv/web/home
      - docker-compose -f docker-compose.yml -f docker-compose.prod.yml down
      - docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d